/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/


INSERT INTO Provinces (Code,Name) VALUES(N'10',N'กรุงเทพมหานคร')
INSERT INTO Provinces (Code,Name) VALUES(N'11',N'สมุทรปราการ')
INSERT INTO Provinces (Code,Name) VALUES(N'12',N'นนทบุรี')
INSERT INTO Provinces (Code,Name) VALUES(N'13',N'ปทุมธานี')
INSERT INTO Provinces (Code,Name) VALUES(N'14',N'อยุธยา')
INSERT INTO Provinces (Code,Name) VALUES(N'15',N'อ่างทอง')
INSERT INTO Provinces (Code,Name) VALUES(N'16',N'ลพบุรี')
INSERT INTO Provinces (Code,Name) VALUES(N'17',N'สิงห์บุรี')
INSERT INTO Provinces (Code,Name) VALUES(N'18',N'ชัยนาท')
INSERT INTO Provinces (Code,Name) VALUES(N'19',N'สระบุรี')
INSERT INTO Provinces (Code,Name) VALUES(N'20',N'ชลบุรี')
INSERT INTO Provinces (Code,Name) VALUES(N'21',N'ระยอง')
INSERT INTO Provinces (Code,Name) VALUES(N'22',N'จันทบุรี')
INSERT INTO Provinces (Code,Name) VALUES(N'23',N'ตราด')
INSERT INTO Provinces (Code,Name) VALUES(N'24',N'ฉะเชิงเทรา')
INSERT INTO Provinces (Code,Name) VALUES(N'25',N'ปราจีนบุรี')
INSERT INTO Provinces (Code,Name) VALUES(N'26',N'นครนายก')
INSERT INTO Provinces (Code,Name) VALUES(N'27',N'สระแก้ว')
INSERT INTO Provinces (Code,Name) VALUES(N'30',N'นครราชสีมา')
INSERT INTO Provinces (Code,Name) VALUES(N'31',N'บุรีรัมย์')
INSERT INTO Provinces (Code,Name) VALUES(N'32',N'สุรินทร์')
INSERT INTO Provinces (Code,Name) VALUES(N'33',N'ศรีสะเกษ')
INSERT INTO Provinces (Code,Name) VALUES(N'34',N'อุบลราชธานี')
INSERT INTO Provinces (Code,Name) VALUES(N'35',N'ยโสธร')
INSERT INTO Provinces (Code,Name) VALUES(N'36',N'ชัยภูมิ')
INSERT INTO Provinces (Code,Name) VALUES(N'37',N'อำนาจเจริญ')
INSERT INTO Provinces (Code,Name) VALUES(N'39',N'หนองบัวลำภู')
INSERT INTO Provinces (Code,Name) VALUES(N'40',N'ขอนแก่น')
INSERT INTO Provinces (Code,Name) VALUES(N'41',N'อุดรธานี')
INSERT INTO Provinces (Code,Name) VALUES(N'42',N'เลย')
INSERT INTO Provinces (Code,Name) VALUES(N'43',N'หนองคาย')
INSERT INTO Provinces (Code,Name) VALUES(N'44',N'มหาสารคาม')
INSERT INTO Provinces (Code,Name) VALUES(N'45',N'ร้อยเอ็ด')
INSERT INTO Provinces (Code,Name) VALUES(N'46',N'กาฬสินธุ์')
INSERT INTO Provinces (Code,Name) VALUES(N'47',N'สกลนคร')
INSERT INTO Provinces (Code,Name) VALUES(N'48',N'นครพนม')
INSERT INTO Provinces (Code,Name) VALUES(N'49',N'มุกดาหาร')
INSERT INTO Provinces (Code,Name) VALUES(N'50',N'เชียงใหม่')
INSERT INTO Provinces (Code,Name) VALUES(N'51',N'ลำพูน')
INSERT INTO Provinces (Code,Name) VALUES(N'52',N'ลำปาง')
INSERT INTO Provinces (Code,Name) VALUES(N'53',N'อุตรดิตถ์')
INSERT INTO Provinces (Code,Name) VALUES(N'54',N'แพร่')
INSERT INTO Provinces (Code,Name) VALUES(N'55',N'น่าน')
INSERT INTO Provinces (Code,Name) VALUES(N'56',N'พะเยา')
INSERT INTO Provinces (Code,Name) VALUES(N'57',N'เชียงราย')
INSERT INTO Provinces (Code,Name) VALUES(N'58',N'แม่ฮ่องสอน')
INSERT INTO Provinces (Code,Name) VALUES(N'60',N'นครสวรรค์')
INSERT INTO Provinces (Code,Name) VALUES(N'61',N'อุทัยธานี')
INSERT INTO Provinces (Code,Name) VALUES(N'62',N'กำแพงเพชร')
INSERT INTO Provinces (Code,Name) VALUES(N'63',N'ตาก')
INSERT INTO Provinces (Code,Name) VALUES(N'64',N'สุโขทัย')
INSERT INTO Provinces (Code,Name) VALUES(N'65',N'พิษณุโลก')
INSERT INTO Provinces (Code,Name) VALUES(N'66',N'พิจิตร')
INSERT INTO Provinces (Code,Name) VALUES(N'67',N'เพชรบูรณ์')
INSERT INTO Provinces (Code,Name) VALUES(N'70',N'ราชบุรี')
INSERT INTO Provinces (Code,Name) VALUES(N'71',N'กาญจนบุรี')
INSERT INTO Provinces (Code,Name) VALUES(N'72',N'สุพรรณบุรี')
INSERT INTO Provinces (Code,Name) VALUES(N'73',N'นครปฐม')
INSERT INTO Provinces (Code,Name) VALUES(N'74',N'สมุทรสาคร')
INSERT INTO Provinces (Code,Name) VALUES(N'75',N'สมุทรสงคราม')
INSERT INTO Provinces (Code,Name) VALUES(N'76',N'เพชรบุรี')
INSERT INTO Provinces (Code,Name) VALUES(N'77',N'ประจวบคีรีขันธ์')
INSERT INTO Provinces (Code,Name) VALUES(N'80',N'นครศรีธรรมราช')
INSERT INTO Provinces (Code,Name) VALUES(N'81',N'กระปี่')
INSERT INTO Provinces (Code,Name) VALUES(N'82',N'พังงา')
INSERT INTO Provinces (Code,Name) VALUES(N'83',N'ภูเก็ต')
INSERT INTO Provinces (Code,Name) VALUES(N'84',N'สุราษฎร์ธานี')
INSERT INTO Provinces (Code,Name) VALUES(N'85',N'ระนอง')
INSERT INTO Provinces (Code,Name) VALUES(N'86',N'ชุมพร')
INSERT INTO Provinces (Code,Name) VALUES(N'90',N'สงขลา')
INSERT INTO Provinces (Code,Name) VALUES(N'91',N'สตูล')
INSERT INTO Provinces (Code,Name) VALUES(N'92',N'ตรัง')
INSERT INTO Provinces (Code,Name) VALUES(N'93',N'พัทลุง')
INSERT INTO Provinces (Code,Name) VALUES(N'94',N'ปัตตานี')
INSERT INTO Provinces (Code,Name) VALUES(N'95',N'ยะลา')
INSERT INTO Provinces (Code,Name) VALUES(N'96',N'นราธิวาส')
INSERT INTO Provinces (Code,Name) VALUES(N'97',N'บึงกาฬ')
INSERT INTO Provinces (Code,Name) VALUES(N'99',N'เบตง')

INSERT INTO Branches (Code,Name) VALUES(N'01',N'test1')
INSERT INTO Branches (Code,Name) VALUES(N'02',N'test2')
INSERT INTO Branches (Code,Name) VALUES(N'03',N'test3')
INSERT INTO Branches (Code,Name) VALUES(N'04',N'test4')
INSERT INTO Branches (Code,Name) VALUES(N'05',N'test5')