//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheS.eExam.DSDAdminRequest.DSA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientAccount
    {
        public int Id { get; set; }
        public string ClientEmail { get; set; }
        public bool IsActivated { get; set; }
        public int AdminRequestId { get; set; }
    
        public virtual AdminRequest AdminRequest { get; set; }
    }
}
