//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheS.eExam.DSDAdminRequest.DSA.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DSDAdminRequestContainer : DbContext
    {
        public DSDAdminRequestContainer()
            : base("name=DSDAdminRequestContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<AdminRequest> AdminRequests { get; set; }
        public virtual DbSet<ClientAccount> ClientAccounts { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
    }
}
